import type { RoleKey } from '@/core/domain/roles'
import type { PermissionAction, PermissionScope, ResourceKey } from '@/core/domain/permissions'

/**
 * RBAC-baslinje: vilka åtgärder en roll får utföra på en resurs, och på vilken
 * maximal räckvidd. ABAC-begränsningar (tenant, klass, relation, tillfällig
 * period, skyddad identitet, klassificering, supportsession) läggs ovanpå i
 * engine.ts. Detta är alltså "taket" – inte hela sanningen.
 */

export interface Grant {
  actions: PermissionAction[]
  scope: PermissionScope
}

export type RoleGrants = Partial<Record<ResourceKey, Grant>>

// Åtgärdsbuntar
const R: PermissionAction[] = ['read']
const RW: PermissionAction[] = ['read', 'create', 'update']
const RWD: PermissionAction[] = ['read', 'create', 'update', 'delete']
const RWX: PermissionAction[] = ['read', 'create', 'update', 'export']
const RWDX: PermissionAction[] = ['read', 'create', 'update', 'delete', 'export']
const MANAGE: PermissionAction[] = ['read', 'create', 'update', 'delete', 'export', 'admin']
const ALL: PermissionAction[] = ['read', 'create', 'update', 'delete', 'export', 'sign', 'admin']

const g = (actions: PermissionAction[], scope: PermissionScope): Grant => ({ actions, scope })

/** Bas som alla inloggade har: se sin egen översikt och notiser. */
const commonBase: RoleGrants = {
  dashboard: g(R, 'egen'),
  notification: g(['read', 'update'], 'egen'),
  settings: g(['read', 'update'], 'egen'),
}

export const ROLE_GRANTS: Record<RoleKey, RoleGrants> = {
  superadmin: {
    ...commonBase,
    dashboard: g(R, 'organisation'),
    organization: g(ALL, 'organisation'),
    school: g(ALL, 'organisation'),
    license: g(MANAGE, 'organisation'),
    integration: g(MANAGE, 'organisation'),
    system_health: g(MANAGE, 'organisation'),
    security: g(MANAGE, 'organisation'),
    audit_log: g(RWX, 'organisation'),
    support_access: g(MANAGE, 'organisation'),
    gdpr: g(RWX, 'organisation'),
    rate_limit: g(MANAGE, 'organisation'),
    feature_flag: g(MANAGE, 'organisation') as Grant,
    // Persondata kräver supportsession (hanteras i engine.ts)
    student: g(R, 'organisation'),
    staff: g(R, 'organisation'),
  },
  huvudman: {
    ...commonBase,
    dashboard: g(R, 'organisation'),
    organization: g(RWX, 'organisation'),
    school: g(RWDX, 'organisation'),
    license: g(RWX, 'organisation'),
    staff: g(RWX, 'organisation'),
    student: g(RWX, 'organisation'),
    report: g(RWX, 'organisation'),
    export: g(RWX, 'organisation'),
    audit_log: g(RWX, 'organisation'),
    gdpr: g(RWX, 'organisation'),
    security: g(RWX, 'organisation'),
    integration: g(RWX, 'organisation'),
    consent: g(RWX, 'organisation'),
    incident: g(RWX, 'organisation'),
    settings: g(RWX, 'organisation'),
  },
  rektor: {
    ...commonBase,
    dashboard: g(R, 'skola'),
    school: g(RWX, 'skola'),
    staff: g(RWDX, 'skola'),
    student: g(RWDX, 'skola'),
    guardian: g(RWX, 'skola'),
    guardian_relation: g(RWX, 'skola'),
    class: g(RWDX, 'skola'),
    course: g(RWDX, 'skola'),
    schedule: g(RWDX, 'skola'),
    attendance: g(RWX, 'skola'),
    absence: g(RWDX, 'skola'),
    assessment: g(RWX, 'skola'),
    incident: g(RWDX, 'skola'),
    consent: g(RWDX, 'skola'),
    documentation: g(RWX, 'skola'),
    file: g(RWDX, 'skola'),
    report: g(RWX, 'skola'),
    export: g(RWX, 'skola'),
    audit_log: g(RWX, 'skola'),
    gdpr: g(RWX, 'skola'),
    security: g(R, 'skola'),
    message: g(RW, 'skola'),
    announcement: g(RWD, 'skola'),
    protected_identity: g(R, 'skola'),
    settings: g(RWX, 'skola'),
    health: g(R, 'skola'),
  },
  bitr_rektor: {
    ...commonBase,
    dashboard: g(R, 'skola'),
    staff: g(RWX, 'skola'),
    student: g(RWX, 'skola'),
    class: g(RWX, 'skola'),
    course: g(RWX, 'skola'),
    schedule: g(RWDX, 'skola'),
    attendance: g(RWX, 'skola'),
    absence: g(RWDX, 'skola'),
    incident: g(RWD, 'skola'),
    consent: g(RWD, 'skola'),
    report: g(RWX, 'skola'),
    export: g(RWX, 'skola'),
    message: g(RW, 'skola'),
    announcement: g(RWD, 'skola'),
    audit_log: g(R, 'skola'),
  },
  skoladmin: {
    ...commonBase,
    dashboard: g(R, 'skola'),
    student: g(RWDX, 'skola'),
    guardian: g(RWDX, 'skola'),
    guardian_relation: g(RWDX, 'skola'),
    staff: g(RWX, 'skola'),
    class: g(RWDX, 'skola'),
    course: g(RWDX, 'skola'),
    schedule: g(RWDX, 'skola'),
    enrollment: g(RWDX, 'skola') as Grant,
    absence: g(RWX, 'skola'),
    attendance: g(RWX, 'skola'),
    consent: g(RWDX, 'skola'),
    file: g(RWDX, 'skola'),
    import: g(MANAGE, 'skola'),
    export: g(RWX, 'skola'),
    report: g(RWX, 'skola'),
    meal: g(RWX, 'skola'),
    message: g(RW, 'skola'),
    announcement: g(RWD, 'skola'),
    pickup: g(RWDX, 'skola'),
  },
  larare: {
    ...commonBase,
    dashboard: g(R, 'klass'),
    student: g(R, 'klass'),
    class: g(R, 'klass'),
    course: g(RW, 'kurs'),
    schedule: g(R, 'klass'),
    attendance: g(RWX, 'klass'),
    absence: g(RW, 'klass'),
    assignment: g(RWDX, 'kurs'),
    assessment: g(RWX, 'kurs'),
    message: g(RW, 'klass'),
    documentation: g(RW, 'klass'),
    incident: g(RW, 'klass'),
    file: g(RW, 'klass'),
    report: g(R, 'klass'),
    announcement: g(RW, 'klass'),
    consent: g(R, 'klass'),
    health: g(R, 'klass'),
    guardian: g(R, 'klass'),
  },
  mentor: {
    ...commonBase,
    dashboard: g(R, 'klass'),
    student: g(RW, 'klass'),
    class: g(RW, 'klass'),
    schedule: g(R, 'klass'),
    attendance: g(RWX, 'klass'),
    absence: g(RWX, 'klass'),
    assessment: g(R, 'klass'),
    message: g(RW, 'klass'),
    documentation: g(RW, 'klass'),
    incident: g(RWD, 'klass'),
    consent: g(RW, 'klass'),
    file: g(RW, 'klass'),
    report: g(RWX, 'klass'),
    guardian: g(RW, 'klass'),
    guardian_relation: g(R, 'klass'),
    health: g(R, 'klass'),
    pickup: g(R, 'klass'),
  },
  pedagog: {
    ...commonBase,
    dashboard: g(R, 'klass'),
    student: g(R, 'klass'),
    class: g(R, 'klass'),
    attendance: g(RWX, 'klass'),
    absence: g(RW, 'klass'),
    documentation: g(RWD, 'klass'),
    message: g(RW, 'klass'),
    consent: g(RW, 'klass'),
    pickup: g(RWX, 'klass'),
    meal: g(R, 'klass'),
    health: g(R, 'klass'),
    file: g(RW, 'klass'),
    incident: g(RW, 'klass'),
  },
  vikarie: {
    ...commonBase,
    dashboard: g(R, 'tillfallig'),
    student: g(R, 'tillfallig'),
    class: g(R, 'tillfallig'),
    schedule: g(R, 'tillfallig'),
    attendance: g(RW, 'tillfallig'),
    absence: g(R, 'tillfallig'),
    message: g(R, 'tillfallig'),
    documentation: g(R, 'tillfallig'),
    health: g(R, 'tillfallig'),
  },
  elev_grund: {
    ...commonBase,
    dashboard: g(R, 'egen'),
    schedule: g(R, 'egen'),
    assignment: g(R, 'egen'),
    message: g(RW, 'egen'),
    documentation: g(R, 'egen'),
    file: g(R, 'egen'),
    meal: g(R, 'skola'),
    attendance: g(R, 'egen'),
  },
  elev_gy: {
    ...commonBase,
    dashboard: g(R, 'egen'),
    schedule: g(R, 'egen'),
    course: g(R, 'egen'),
    assignment: g(['read', 'create', 'update'], 'egen'),
    assessment: g(R, 'egen'),
    absence: g(R, 'egen'),
    attendance: g(R, 'egen'),
    message: g(RW, 'egen'),
    file: g(R, 'egen'),
    report: g(R, 'egen'),
  },
  vardnadshavare: {
    ...commonBase,
    dashboard: g(R, 'relation'),
    student: g(R, 'relation'),
    schedule: g(R, 'relation'),
    absence: g(RW, 'relation'),
    attendance: g(R, 'relation'),
    assessment: g(R, 'relation'),
    message: g(RW, 'relation'),
    documentation: g(R, 'relation'),
    consent: g(['read', 'sign'], 'relation'),
    file: g(R, 'relation'),
    pickup: g(RW, 'relation'),
    incident: g(R, 'relation'),
    meal: g(R, 'relation'),
    guardian: g(['read', 'update'], 'egen'),
    health: g(R, 'relation'),
  },
  specialpedagog: {
    ...commonBase,
    dashboard: g(R, 'skola'),
    student: g(RW, 'skola'),
    documentation: g(RWDX, 'elev'),
    incident: g(RWD, 'skola'),
    assessment: g(R, 'skola'),
    absence: g(R, 'skola'),
    attendance: g(R, 'skola'),
    message: g(RW, 'skola'),
    file: g(RWD, 'elev'),
    health: g(R, 'elev'),
    report: g(RWX, 'skola'),
    consent: g(R, 'skola'),
    protected_identity: g(R, 'elev'),
  },
  kurator: {
    ...commonBase,
    dashboard: g(R, 'skola'),
    student: g(R, 'skola'),
    documentation: g(RWDX, 'elev'),
    incident: g(RWDX, 'skola'),
    message: g(RW, 'skola'),
    file: g(RWD, 'elev'),
    health: g(R, 'elev'),
    report: g(RWX, 'skola'),
    protected_identity: g(R, 'elev'),
    gdpr: g(R, 'skola'),
  },
  skolskoterska: {
    ...commonBase,
    dashboard: g(R, 'skola'),
    student: g(R, 'skola'),
    health: g(RWDX, 'elev'),
    documentation: g(RWD, 'elev'),
    incident: g(RW, 'skola'),
    message: g(RW, 'skola'),
    file: g(RWD, 'elev'),
    consent: g(R, 'skola'),
    report: g(RWX, 'skola'),
    protected_identity: g(R, 'elev'),
  },
  syv: {
    ...commonBase,
    dashboard: g(R, 'skola'),
    student: g(R, 'skola'),
    course: g(R, 'skola'),
    assessment: g(R, 'skola'),
    documentation: g(RW, 'elev'),
    message: g(RW, 'skola'),
    file: g(RW, 'elev'),
    report: g(RWX, 'skola'),
  },
  koksansvarig: {
    ...commonBase,
    dashboard: g(R, 'skola'),
    meal: g(RWDX, 'skola'),
    // Endast anonymiserad specialkost/allergi, ingen persondata (engine maskerar)
    health: g(R, 'skola'),
    report: g(RWX, 'skola'),
    message: g(R, 'skola'),
  },
  it_support: {
    ...commonBase,
    dashboard: g(R, 'skola'),
    staff: g(RW, 'skola'),
    integration: g(RWX, 'organisation'),
    system_health: g(R, 'organisation'),
    security: g(RWX, 'organisation'),
    audit_log: g(RWX, 'organisation'),
    support_access: g(RW, 'organisation'),
    rate_limit: g(RWX, 'organisation'),
    import: g(RW, 'skola'),
    export: g(R, 'skola'),
    settings: g(RWX, 'skola'),
    // Persondata kräver supportsession
    student: g(R, 'skola'),
  },
  granskare: {
    ...commonBase,
    dashboard: g(R, 'organisation'),
    audit_log: g(R, 'organisation'),
    gdpr: g(R, 'organisation'),
    security: g(R, 'organisation'),
    report: g(R, 'organisation'),
    consent: g(R, 'organisation'),
    integration: g(R, 'organisation'),
    license: g(R, 'organisation'),
    // Endast läsning, aldrig export av persondata (engine blockerar export)
  },
  integration_bot: {
    student: g(['read', 'create', 'update'], 'organisation'),
    guardian: g(['read', 'create', 'update'], 'organisation'),
    staff: g(['read', 'create', 'update'], 'organisation'),
    class: g(['read', 'create', 'update'], 'organisation'),
    course: g(['read', 'create', 'update'], 'organisation'),
    schedule: g(['read', 'create', 'update'], 'organisation'),
    enrollment: g(['read', 'create', 'update'], 'organisation') as Grant,
    attendance: g(['read', 'create'], 'organisation'),
    integration: g(R, 'organisation'),
  },
}
